@tool
extends EditorPlugin

func _enter_tree() -> void:
	add_custom_type(
		"IconBase",
		"Control",
		load("uid://bfg5x70yt7pii"),
		load("uid://m1lrpw6a643c")
	)
	
	add_custom_type(
		"AntDesign",
		"Control",
		load("uid://dyhhvqcy300sm"),
		load("uid://wrl11vgjareu")
	)
	add_custom_type(
		"Entypo",
		"Control",
		load("uid://l2q4q4vnluob"),
		load("uid://d2hnpywqc6hqi")
	)
	add_custom_type(
		"EvilIcons",
		"Control",
		load("uid://8bjt6f1ip3oj"),
		load("uid://de0wbn1f77ium")
	)
	add_custom_type(
		"Feather",
		"Control",
		load("uid://b58the6pio4w"),
		load("uid://cx80m6b6eueth")
	)
	add_custom_type(
		"FontAwesome5",
		"Control",
		load("uid://uo0ns2lhrhkd"),
		load("uid://bjbly7atqtx4l")
	)
	add_custom_type(
		"FontAwesome6",
		"Control",
		load("uid://cxqnbfkn4sque"),
		load("uid://2sk8xnu81yqq")
	)
	add_custom_type(
		"FontAwesome",
		"Control",
		load("uid://ouh2uorb4gmr"),
		load("uid://y5b013krct4w")
	)
	add_custom_type(
		"Fontisto",
		"Control",
		load("uid://c6iw3dpi5q7va"),
		load("uid://dl1mxqni5y21y")
	)
	add_custom_type(
		"Foundation",
		"Control",
		load("uid://18fl8skgouv8"),
		load("uid://cixhyyfmy76vq")
	)
	add_custom_type(
		"Ionicons",
		"Control",
		load("uid://bw124ti4smdn4"),
		load("uid://b67y8hrptj7it")
	)
	add_custom_type(
		"MaterialCommunityIcons",
		"Control",
		load("uid://sssi1oere6n7"),
		load("uid://1st7fekoufae")
	)
	add_custom_type(
		"MaterialIcons",
		"Control",
		load("uid://58tcc605ihw2"),
		load("uid://bge8aaymmky5a")
	)
	add_custom_type(
		"Octicons",
		"Control",
		load("uid://ottnvo0s64il"),
		load("uid://ddfxphj6o0q60")
	)
	add_custom_type(
		"SimpleLineIcons",
		"Control",
		load("uid://cvqvpsswcy6ph"),
		load("uid://c2mm8wufceupk")
	)
	add_custom_type(
		"Zocial",
		"Control",
		load("uid://bmxo2408u6o0w"),
		load("uid://d252n60c2wkaf")
	)

func _exit_tree() -> void:
	remove_custom_type("Zocial")
	remove_custom_type("SimpleLineIcons")
	remove_custom_type("Octicons")
	remove_custom_type("MaterialIcons")
	remove_custom_type("MaterialCommunityIcons")
	remove_custom_type("Foundation")
	remove_custom_type("Fontisto")
	remove_custom_type("FontAwesome")
	remove_custom_type("FontAwesome6")
	remove_custom_type("FontAwesome5")
	remove_custom_type("Feather")
	remove_custom_type("EvilIcons")
	remove_custom_type("Entypo")
	remove_custom_type("AntDesign")
	
	remove_custom_type("IconBase")
